"""Generated from protocol/schemas/. Do not edit by hand.

Regenerate with `python3 tools/gen_models.py`; `make schema` fails if this drifts from the
schema it was generated from. A schema change is a protocol change and requires bumping
`protocol_version`.
"""

# generated by datamodel-codegen:
#   filename:  bundle_manifest.json

from __future__ import annotations

from typing import Literal

from protocol.model_base import ProtocolModel
from pydantic import ConfigDict, Field, constr


class BundleManifest(ProtocolModel):
    """
    The submission unit's declaration, from architecture.md section 5.2. One complete versioned AutonomousInventionLabBundle.

    Every hash here exists so that what a validator executes is provably what the miner committed. `container_digest` is a digest and never a tag: a tag is mutable, and a mutable reference means the artifact executed is not the artifact sealed.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: Literal['AIL-3.0']
    bundle_id: constr(pattern=r'^[0-9a-zA-Z]+/[0-9a-zA-Z._-]+$', max_length=200) = (
        Field(
            ...,
            description='`{miner_hotkey}/{lab_name}`. Namespaced by hotkey so two miners cannot collide, and stable across versions so lineage is traceable (section 22 publishes bundle lineage and forks).',
        )
    )
    bundle_version: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$')
    round_id: constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}$') = Field(
        ...,
        description='The daily round this bundle targets, as a date. The cycle is daily (section 21), so a bundle names a day rather than a season.',
    )
    entrypoint: constr(min_length=1, max_length=500)
    container_digest: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    source_archive_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    lockfile_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    sbom_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    license: constr(min_length=1, max_length=100)
    supported_domains: list[str] = Field(
        ...,
        description='Which taxonomy domains this laboratory accepts. A challenge outside the declared set is not scored against it — a laboratory is not penalised for a domain it never claimed.',
        max_length=20,
        min_length=1,
    )
    output_schema: Literal['research_portfolio_v1']
    resource_class: constr(max_length=50) | None = Field(
        None,
        description='Requested sandbox size, from the allowed classes the owner publishes (section 3.3).',
    )
    miner_signature: constr(min_length=1, max_length=500)
    credential_envelope_digest: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        description='Content address of the sealed OpenRouter credential envelope (architecture.md section 5.4.1). The digest is here so the manifest commits to which envelope belongs to it; the envelope itself is a separate sealed object.\n\nSeparate rather than inline, and the separation is the control: section 6.3 publishes this manifest after execution closes, and a credential inside it would be published with it. A distinct object can be excluded by construction -- the publication path never reads it -- rather than by a filter someone must remember to keep correct.',
    )
