"""Generated from protocol/schemas/. Do not edit by hand.

Regenerate with `python3 tools/gen_models.py`; `make schema` fails if this drifts from the
schema it was generated from. A schema change is a protocol change and requires bumping
`protocol_version`.
"""

# generated by datamodel-codegen:
#   filename:  challenge.json

from __future__ import annotations

from enum import Enum

from protocol.model_base import ProtocolModel
from pydantic import ConfigDict, Field, RootModel, conint, constr


class Domain(Enum):
    """
    A member of the active taxonomy. Restricted in V1 to domains an LLM panel can inspect without a physical laboratory.
    """

    software_architecture = 'software_architecture'
    algorithms = 'algorithms'
    ai_agent_architecture = 'ai_agent_architecture'
    memory_and_retrieval = 'memory_and_retrieval'
    distributed_coordination = 'distributed_coordination'
    digital_mechanism_design = 'digital_mechanism_design'
    data_and_model_pipelines = 'data_and_model_pipelines'
    optimization_and_efficiency = 'optimization_and_efficiency'


class RequiredOutput(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    portfolio_size: conint(ge=1, le=10)
    ranked: bool
    mechanism_required: bool
    prior_art_comparison_required: bool
    falsification_plan_required: bool
    simulation_or_calculation_required: bool


class ResourceLimits(ProtocolModel):
    """
    The equal budget every laboratory in the cohort receives. Equality is the control against brute-force capital.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    maximum_wall_time_seconds: conint(ge=60, le=14400)
    maximum_rcc: conint(ge=1)
    maximum_search_calls: conint(ge=0)


class Challenge(ProtocolModel):
    """
    One structured research problem. Generated by a validator, hash-committed before any miner runs, and private until evaluation closes. There is no simulated user and no conversational persona: a challenge is a single structured research request. Every field is integer or string so that a challenge pack hashes reproducibly.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    challenge_id: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        description='Content address of the challenge. Derived from the challenge body, so it cannot be chosen.',
    )
    domain: Domain = Field(
        ...,
        description='A member of the active taxonomy. Restricted in V1 to domains an LLM panel can inspect without a physical laboratory.',
    )
    title: constr(min_length=8, max_length=200)
    problem_statement: constr(min_length=200, max_length=20000) = Field(
        ...,
        description='The problem as the laboratory receives it. The linter rejects a challenge whose statement is not clearly stated.',
    )
    research_objective: constr(min_length=50, max_length=4000) = Field(
        ...,
        description='What a good answer must achieve. Distinct from the problem statement: the objective is what the Constraint Judge scores against.',
    )
    current_baseline: constr(max_length=8000) | None = Field(
        None,
        description="How the problem is addressed today. Present so that 'materially different from prior art' has a stated reference rather than an implied one.",
    )
    known_attempts: list[constr(max_length=2000)] | None = Field(
        None,
        description='Approaches already tried and their outcomes. A laboratory that re-proposes one of these has not invented.',
        max_length=20,
    )
    constraints: list[constr(max_length=1000)] = Field(
        ...,
        description='Hard requirements. The linter rejects a challenge with none: without constraints there is nothing for a mechanism to satisfy and nothing for the Constraint Judge to check.',
        max_length=30,
        min_length=1,
    )
    forbidden_shortcuts: list[constr(max_length=1000)] | None = Field(
        None,
        description='Solutions that trivially satisfy the constraints without inventing. Named explicitly so that a laboratory taking one fails the objective rather than scoring well on a technicality.',
        max_length=20,
    )
    required_output: RequiredOutput
    resource_limits: ResourceLimits = Field(
        ...,
        description='The equal budget every laboratory in the cohort receives. Equality is the control against brute-force capital.',
    )
    generator_family: constr(max_length=50) = Field(
        ...,
        description="Which family generated this problem. Recorded per challenge so a miner's score can be split by generator: a laboratory scoring far better on one family has learned a generator, not a domain, and that gap is the earliest signal the challenge supply has become predictable.\n\nCommitted with the pack, but the per-slot split is not published before execution -- otherwise a laboratory would know which half of the day to expect from whom.",
    )
    critic_family: constr(max_length=50) | None = Field(
        None,
        description="Which family reviewed it. Must differ from generator_family: same-family critique is close to self-review, since a model shares its generator's blind spots.",
    )
