"""Generated from protocol/schemas/. Do not edit by hand.

Regenerate with `python3 tools/gen_models.py`; `make schema` fails if this drifts from the
schema it was generated from. A schema change is a protocol change and requires bumping
`protocol_version`.
"""

# generated by datamodel-codegen:
#   filename:  execution_receipt.json

from __future__ import annotations

from enum import Enum

from protocol.model_base import ProtocolModel
from pydantic import ConfigDict, Field, RootModel, conint, constr


class Totals(ProtocolModel):
    """
    Gateway-measured, never miner-reported. Validators replace self-reported usage with measured usage.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rcc: conint(ge=0)
    model_calls: conint(ge=0)
    search_calls: conint(ge=0)
    tokens_in: conint(ge=0) | None = None
    tokens_out: conint(ge=0) | None = None
    wall_time_seconds: conint(ge=0) | None = None


class CredentialOwner(Enum):
    """
    Whose OpenRouter account funded these calls. Recorded on every receipt because the two accounts are the only thing separating miner research from validator judging -- and with a single provider surface, a swapped key succeeds and silently bills the wrong party rather than failing on the first request.

    This field is what makes that detectable: because both accounts report usage in the same format, per-account totals can be reconciled against provider-reported usage. A call billed to the wrong account is an incident, and it is the one defect the API itself will not surface.
    """

    miner = 'miner'
    validator = 'validator'


class ProviderReportedUsage(ProtocolModel):
    """
    Usage as the provider itself reports it, for reconciliation against `totals`. Receipt reconciliation must be exact; a discrepancy means the meter and the provider disagree about what was spent on a miner's credential, which is the one signal that catches a validator spending outside the receipted path.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rcc: conint(ge=0) | None = None
    cost_micro_usd: conint(ge=0) | None = None
    requests: conint(ge=0) | None = None


class Purpose(Enum):
    """
    What the call was for. Purpose selects the credential, so a research call cannot reach the validator resolver and a judging call cannot reach the miner resolver. Recorded so the selection is auditable after the fact, not merely asserted in code.
    """

    research = 'research'
    search = 'search'
    simulation = 'simulation'
    challenge_generation = 'challenge_generation'
    critique = 'critique'
    judging = 'judging'
    prior_art = 'prior_art'


class Tool(Enum):
    llm = 'llm'
    search = 'search'
    sim = 'sim'
    embedding = 'embedding'
    code = 'code'


class Call(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    seq: conint(ge=0)
    tool: Tool
    provider: constr(max_length=100)
    model: constr(max_length=200) | None = None
    revision: constr(max_length=100) | None = None
    request_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    response_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    rcc: conint(ge=0)
    tokens_in: conint(ge=0) | None = None
    tokens_out: conint(ge=0) | None = None
    attempts: conint(ge=1) | None = Field(
        None,
        description='Attempts that may have consumed provider budget, including failures. A retry storm must not be free.',
    )
    previous: constr(pattern=r'^(sha256:[0-9a-f]{64}|genesis)$') = Field(
        ..., description='The previous link, or the genesis marker for the first call.'
    )


class ExecutionReceipt(ProtocolModel):
    """
    The gateway's signed record of one laboratory's external calls.

    Hash-chained: each entry commits to the previous one, so a receipt cannot be removed or reordered after the fact without breaking every link after it. That is what makes 'budget exceeded' and 'unauthorized endpoint' hard gates provable rather than asserted, and what makes execution-receipt reconciliation measurable.

    Request and response bodies are recorded as hashes, never as content. The gateway must be able to prove what was asked without becoming an archive of every prompt a miner ever wrote.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: constr(max_length=200)
    miner_hotkey: constr(max_length=100)
    bundle_digest: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    challenge_id: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    validator_hotkey: constr(max_length=100)
    calls: list[Call] = Field(..., max_length=10000)
    totals: Totals = Field(
        ...,
        description='Gateway-measured, never miner-reported. Validators replace self-reported usage with measured usage.',
    )
    chain_head: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        description='Hash over the final call, and therefore over every call before it.',
    )
    signature: constr(min_length=1, max_length=500)
    credential_owner: CredentialOwner = Field(
        ...,
        description='Whose OpenRouter account funded these calls. Recorded on every receipt because the two accounts are the only thing separating miner research from validator judging -- and with a single provider surface, a swapped key succeeds and silently bills the wrong party rather than failing on the first request.\n\nThis field is what makes that detectable: because both accounts report usage in the same format, per-account totals can be reconciled against provider-reported usage. A call billed to the wrong account is an incident, and it is the one defect the API itself will not surface.',
    )
    provider_reported_usage: ProviderReportedUsage | None = Field(
        None,
        description="Usage as the provider itself reports it, for reconciliation against `totals`. Receipt reconciliation must be exact; a discrepancy means the meter and the provider disagree about what was spent on a miner's credential, which is the one signal that catches a validator spending outside the receipted path.",
    )
    purpose: Purpose = Field(
        ...,
        description='What the call was for. Purpose selects the credential, so a research call cannot reach the validator resolver and a judging call cannot reach the miner resolver. Recorded so the selection is auditable after the fact, not merely asserted in code.',
    )
