"""Generated from protocol/schemas/. Do not edit by hand.

Regenerate with `python3 tools/gen_models.py`; `make schema` fails if this drifts from the
schema it was generated from. A schema change is a protocol change and requires bumping
`protocol_version`.
"""

# generated by datamodel-codegen:
#   filename:  model_manifest.json

from __future__ import annotations

from enum import Enum
from typing import Any

from protocol.model_base import ProtocolModel
from pydantic import ConfigDict, Field, conint, constr


class Provider(Enum):
    """
    The provider surface. OpenRouter for every call in the subnet, miner and validator alike; the enum is closed so a laboratory cannot name a route the gateway has no adapter for. Separation between the two sides is by account, not by provider.
    """

    openrouter = 'openrouter'


class Role(Enum):
    idea_generation = 'idea_generation'
    critique = 'critique'
    prior_art = 'prior_art'
    ranking = 'ranking'
    planning = 'planning'
    synthesis = 'synthesis'
    simulation = 'simulation'
    other = 'other'


class Model(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alias: constr(min_length=1, max_length=100) = Field(
        ...,
        description="The laboratory's internal name for this model. What its own code calls; the gateway resolves it to the declaration.",
    )
    provider: Provider = Field(
        ...,
        description='The provider surface. OpenRouter for every call in the subnet, miner and validator alike; the enum is closed so a laboratory cannot name a route the gateway has no adapter for. Separation between the two sides is by account, not by provider.',
    )
    hf_repo: constr(max_length=200) | None = Field(
        None,
        description='For a miner-owned model. Chutes can deploy a Hugging Face model behind an OpenAI-compatible API pinned to a revision, which is what makes a private fine-tune verifiable.',
    )
    revision: constr(pattern=r'^[0-9a-f]{40}$') | None = Field(
        None,
        description='A full 40-character commit SHA. Abbreviated revisions are refused: an abbreviation can become ambiguous as a repository grows, and the point of pinning is that it cannot.',
    )
    model_snapshot: constr(max_length=200) | None = Field(
        None,
        description='The season-fixed version of the route. A provider that silently moves a slug changes what every laboratory is running mid-season, so the snapshot rather than the slug is the identity the gateway enforces.',
    )
    parameters: dict[str, Any] | None = Field(
        None,
        description="Sampling parameters, pinned. Temperature is part of a laboratory's design, so changing it after the deadline would change the submission.",
    )
    role: Role
    model_slug: constr(min_length=1, max_length=200) = Field(
        ...,
        description='The OpenRouter route, e.g. `anthropic/claude-sonnet-4.5`. Identifies which model; `model_snapshot` pins which version of it.',
    )


class ModelManifest(ProtocolModel):
    """
    Every externally invoked model, declared before submission closes. Every model is reached through OpenRouter, which is the single miner-facing provider surface, but the selection behind it is unrestricted: Anthropic, OpenAI, Google, Meta, Mistral, open-weight hosts, or a private fine-tune the miner routes through.

    One surface for three reasons: model choice stays open, usage arrives in one accounting format (which is what makes an equal RCC ceiling comparable between two laboratories that chose different models), and model pinning has one place to be right rather than one per provider adapter.

    The declaration is closed even though the choice is open: after the deadline a laboratory cannot change which models it calls, at which snapshots, with which parameters. That is what makes 'undeclared model use' and 'model-revision mismatch' hard gates rather than opinions -- the gateway enforces the declaration at call time, and an undeclared model cannot be reached at all.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    models: list[Model] = Field(..., max_length=40, min_length=1)
    routing_config_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        description='Content address of the routing configuration. Pinned so that which model handles which role cannot change after the deadline, even when the model set does not.',
    )
    maximum_parallel_calls: conint(ge=1, le=128) | None = None
