"""Generated from protocol/schemas/. Do not edit by hand.

Regenerate with `python3 tools/gen_models.py`; `make schema` fails if this drifts from the
schema it was generated from. A schema change is a protocol change and requires bumping
`protocol_version`.
"""

# generated by datamodel-codegen:
#   filename:  portfolio.json

from __future__ import annotations

from protocol.model_base import ProtocolModel
from pydantic import ConfigDict, Field, RootModel, confloat, conint, constr


class LaboratorySummary(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    research_strategy: constr(max_length=8000) | None = None
    search_scope: constr(max_length=4000) | None = None
    major_assumptions: list[constr(max_length=1000)] | None = Field(None, max_length=20)


class PortfolioMap(ProtocolModel):
    """
    The laboratory's own account of how its ideas differ. Scored by the Diversity Judge against the canonicalizer's independent clustering, so a claimed difference that clustering does not find counts against it.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    idea_families: list[constr(max_length=500)] | None = Field(None, max_length=10)
    differences: list[constr(max_length=2000)] | None = Field(None, max_length=45)


class SelfSelection(ProtocolModel):
    """
    Why the laboratory ranked its first idea first. Scored by the Self-Selection Judge against which idea the panel would have picked.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    why_rank_1: constr(min_length=20, max_length=8000)
    confidence: confloat(ge=0.0, le=1.0) | None = None


class ResourceUsageClaim(ProtocolModel):
    """
    The laboratory's own account of what it spent. Recorded but never trusted: validators replace self-reported usage with gateway-measured usage. Kept because a claim that disagrees with measurement is itself evidence.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rcc: conint(ge=0) | None = None
    search_calls: conint(ge=0) | None = None
    model_calls: conint(ge=0) | None = None


class Mechanism(ProtocolModel):
    """
    Why the idea works. A mechanism below the mechanism floor caps both value and originality at 0.50 — an idea cannot score highly merely by sounding unusual.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    components: list[constr(max_length=1000)] = Field(..., max_length=30, min_length=1)
    information_flow: constr(max_length=8000) | None = None
    causal_explanation: constr(min_length=50, max_length=12000)
    feedback_loops: list[constr(max_length=2000)] | None = Field(None, max_length=20)


class NearestPriorArtItem(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: constr(max_length=2000)
    similarity: constr(max_length=1000) | None = None
    material_difference: constr(max_length=4000)


class ExpectedValue(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    beneficiary: constr(max_length=1000) | None = None
    value_created: constr(max_length=4000) | None = None
    magnitude_hypothesis: constr(max_length=4000) | None = None


class SimulationOrCalculation(ProtocolModel):
    """
    The one place a claim can be checked rather than judged. Artifacts are referenced by content address so a validator can re-verify the stated result.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    method: constr(max_length=4000) | None = None
    result: constr(max_length=8000) | None = None
    artifact_refs: list[constr(max_length=500)] | None = Field(None, max_length=20)


class Idea(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rank: conint(ge=1, le=10)
    title: constr(min_length=4, max_length=300)
    problem_reframe: constr(max_length=4000) | None = None
    core_invention: constr(min_length=50, max_length=12000)
    mechanism: Mechanism = Field(
        ...,
        description='Why the idea works. A mechanism below the mechanism floor caps both value and originality at 0.50 — an idea cannot score highly merely by sounding unusual.',
    )
    nearest_prior_art: list[NearestPriorArtItem] | None = Field(
        None,
        description="The laboratory's own prior-art comparison. Verified independently: a fabricated or inaccessible citation is a hard-gate failure, not a scoring deduction.",
        max_length=20,
    )
    why_non_obvious: constr(min_length=20, max_length=8000)
    expected_value: ExpectedValue | None = None
    assumptions: list[constr(max_length=2000)] | None = Field(None, max_length=30)
    weakest_assumption: constr(max_length=4000) | None = None
    failure_modes: list[constr(max_length=2000)] | None = Field(None, max_length=30)
    falsifiable_predictions: list[constr(max_length=4000)] | None = Field(
        None,
        description='Discriminating predictions. Scored by the Falsifiability Judge; a deepening with no falsifiable result scores zero on that axis.',
        max_length=20,
    )
    cheapest_kill_test: constr(max_length=4000) | None = None
    simulation_or_calculation: SimulationOrCalculation | None = Field(
        None,
        description='The one place a claim can be checked rather than judged. Artifacts are referenced by content address so a validator can re-verify the stated result.',
    )
    development_path: list[constr(max_length=2000)] | None = Field(None, max_length=20)
    estimated_probability_of_value: confloat(ge=0.0, le=1.0) | None = None
    estimated_validation_cost_rcc: conint(ge=0) | None = None


class ResearchPortfolio(ProtocolModel):
    """
    What a laboratory returns: a ranked Top-N invention portfolio. Schema name `research_portfolio_v1`.

    Two fields are numeric probabilities the miner supplies (`estimated_probability_of_value`, `self_selection.confidence`). They are permitted here because this schema describes the raw artifact as it arrives, and the raw artifact is hashed as *received bytes* rather than as a re-encoded object. The canonicalizer converts them to integer fixed-point before anything scores or hashes a derived form, so no float ever reaches an arithmetic path that two runs must agree on.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    challenge_id: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    laboratory_summary: LaboratorySummary | None = None
    portfolio: list[Idea] = Field(..., max_length=10, min_length=1)
    portfolio_map: PortfolioMap | None = Field(
        None,
        description="The laboratory's own account of how its ideas differ. Scored by the Diversity Judge against the canonicalizer's independent clustering, so a claimed difference that clustering does not find counts against it.",
    )
    self_selection: SelfSelection = Field(
        ...,
        description='Why the laboratory ranked its first idea first. Scored by the Self-Selection Judge against which idea the panel would have picked.',
    )
    resource_usage_claim: ResourceUsageClaim | None = Field(
        None,
        description="The laboratory's own account of what it spent. Recorded but never trusted: validators replace self-reported usage with gateway-measured usage. Kept because a claim that disagrees with measurement is itself evidence.",
    )
