"""Generated from protocol/schemas/. Do not edit by hand.

Regenerate with `python3 tools/gen_models.py`; `make schema` fails if this drifts from the
schema it was generated from. A schema change is a protocol change and requires bumping
`protocol_version`.
"""

# generated by datamodel-codegen:
#   filename:  season_config.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Literal

from protocol.model_base import ProtocolModel
from pydantic import ConfigDict, Field, RootModel, conint, constr


class Taxonomy(ProtocolModel):
    """
    The active domain set and the per-day stratification. V1 is restricted to domains an LLM panel can inspect without a physical laboratory.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    domains: list[str] = Field(..., max_length=32, min_length=1)
    challenges_per_day: conint(ge=1, le=64)
    stratification: dict[str, conint(ge=0)] = Field(
        ...,
        description='How many challenges each domain contributes per day. Must sum to `challenges_per_day`; a wildcard slot is expressed as the reserved domain name `wildcard`.',
    )
    excluded_domains: list[str] | None = Field(
        None,
        description='The V1 exclusions, named rather than merely omitted, so the safety filter has a list to check against.',
        max_length=32,
    )


class ResourceClass(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(max_length=50)
    memory_bytes: conint(ge=1)
    cpu_shares: conint(ge=1)
    pids_limit: conint(ge=1)
    workspace_bytes: conint(ge=0) | None = None


class Provider(Enum):
    """
    Always OpenRouter. Kept as a field rather than omitted so a future second surface is a schema change rather than a silent assumption.
    """

    openrouter = 'openrouter'


class Generator(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: constr(max_length=50)
    provider: Provider = Field(
        ...,
        description='Always OpenRouter. Kept as a field rather than omitted so a future second surface is a schema change rather than a silent assumption.',
    )
    model_snapshot: constr(max_length=200) = Field(
        ...,
        description="The immutable route to send for this generator family. Validator-side and therefore the owner's choice; miners are not pinned by the season.",
    )
    slots: conint(ge=1)
    critic_family: constr(max_length=50) = Field(
        ...,
        description="Which family reviews this one's output. Must not be the family itself: same-family critique is close to self-review, since a model shares its generator's blind spots and rates its own family's output as well-formed. Crossing them is the only version of the check that finds an ambiguity the writer could not see.",
    )
    model_slug: constr(min_length=1, max_length=200) = Field(
        ...,
        description='The OpenRouter route, e.g. `openai/gpt-5`. `model_snapshot` pins which version of it.',
    )


class Backend(Enum):
    redis = 'redis'


class Store(ProtocolModel):
    """
    Where generated packs live. Redis: write a pack once, read it many times during execution, expire it after the dedup window, and survive a restart mid-round without losing a pack whose hash is already committed.

    `sandbox_reachable` must be false. A laboratory that could reach the store would read the entire pack -- every problem including ones it has not been issued, and other rounds' packs. The store is the validator's; delivery to the laboratory is the runner's, as its structured input.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    backend: Backend
    sandbox_reachable: Literal[False]
    pack_ttl_days: conint(ge=1) | None = None


class ChallengeGeneration(ProtocolModel):
    """
    The generation pipeline's parameters. The discrimination probe is the load-bearing one: it is what stops a validator producing problems nobody can be scored on.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: constr(max_length=50)
    candidates_per_slot: conint(ge=1, le=10)
    dedup_lookback_days: conint(ge=1)
    duplicate_threshold_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='Similarity at or above which a candidate is a duplicate. 850000 = 0.85.',
    )
    minimum_reference_spread_ppm: conint(ge=0, le=1000000) | None = Field(
        None,
        description='Reference labs must disagree by at least this much, or the problem does not discriminate, and the discrimination probe rejects it.',
    )
    generator_model_snapshots: list[str] | None = Field(None, max_length=10)
    generators: list[Generator] = Field(
        ...,
        description="The two generator families and how many of the day's slots each owns. Two rather than one because a single generator has a house style: it reaches for the same problem shapes and constraint patterns, and a laboratory tuned to that style scores well without being better. With half the pack from each family, half is always foreign to whatever a miner overfitted to -- and the gap between a miner's two halves is itself the earliest signal that the challenge supply has become predictable.",
        min_length=2,
    )
    store: Store = Field(
        ...,
        description="Where generated packs live. Redis: write a pack once, read it many times during execution, expire it after the dedup window, and survive a restart mid-round without losing a pack whose hash is already committed.\n\n`sandbox_reachable` must be false. A laboratory that could reach the store would read the entire pack -- every problem including ones it has not been issued, and other rounds' packs. The store is the validator's; delivery to the laboratory is the runner's, as its structured input.",
    )
    minimum_degradation_gap_ppm: conint(ge=1, le=1000000) = Field(
        ...,
        description="7.4 step 5 condition 5: the smallest gap, in ppm, between a judge panel's score for an intact portfolio and its score for a deliberately degraded one, below which the problem is rejected. The sharpest of the five conditions — spread among real answers can be noise, but a panel that cannot tell a damaged portfolio from a whole one was never measuring quality. Declared here rather than defaulted in code, because a threshold that decides which challenges enter a hashed pack must be part of the hashed config.",
    )
    maximum_judge_instability_ppm: conint(ge=1, le=1000000) = Field(
        ...,
        description='7.4 step 5 condition 3: the largest spread, in ppm, between repeated judgings of the *same* portfolio that a problem may produce. Above it the panel disagrees with itself, so its scores on real answers are noise.',
    )
    allow_unprobed_packs: bool = Field(
        ...,
        description="Whether a pack generated without 7.4 step 5's discrimination probe may be committed. False everywhere it matters. True is a deliberate testnet degradation: the probe needs reference-laboratory runs and a judge panel, so a network standing them up may need to generate packs before they exist. An unprobed pack may contain problems on which every laboratory is equal, which yields a day's ranking made of noise rather than a day with no ranking — the second is recoverable and the first is not, because it is indistinguishable from a real result.",
    )


class Funnel(ProtocolModel):
    """
    The evaluation funnel. Every valid response gets the cheap anchored pointwise screen; only the cohort gets the expensive pairwise tournament. These numbers decide both what a round costs the validator and how much incumbency the ranking permits, which is why they are season configuration rather than constants: cohort_random and cohort_new exist so that being outside the top cannot become self-perpetuating.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    cohort_top: conint(ge=2) = Field(
        ..., description='Highest-screening laboratories admitted to full evaluation.'
    )
    cohort_random: conint(ge=0) = Field(
        ...,
        description="Randomly drawn from the rest, seeded from the day's seed so it is reproducible and unpredictable in advance. Prevents incumbent lock-in.",
    )
    cohort_new: conint(ge=0) = Field(
        ...,
        description='Laboratories with no rolling history, admitted regardless of screen. A new entrant cannot screen well against incumbents it has never been compared with.',
    )
    swiss_rounds: conint(ge=1) = Field(
        ...,
        description='Pairing rounds per challenge. Each is one pair of judged comparisons per pairing, in both presentation orders.',
    )
    prior_art_ideas_per_portfolio: conint(ge=0) = Field(
        ...,
        description='Ideas per portfolio given a prior-art report (15). Reports are built for the cohort only, after screening, because the search is the expensive half of judging.',
    )


class Provider1(Enum):
    openrouter = 'openrouter'


class Judge(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: constr(max_length=50) = Field(
        ...,
        description="Who trained the model behind the route, not the aggregator. Every judge is reached through OpenRouter, so reading 'provider' as the family would make the 40% cap vacuous: three routes to three Anthropic snapshots is one family and violates the cap however many distinct slugs it uses. The cap is evaluated on this field, which is why it is required rather than derived from the slug.",
    )
    provider: Provider1
    model_snapshot: constr(max_length=200) = Field(
        ...,
        description="The immutable route to send for this judge. Where a provider publishes dated variants, the dated slug; where it does not, the slug itself. Validator-side models are the owner's choice and are current rather than frozen across seasons — see 5.3. The same panel judges every laboratory in a cohort on a given day, so a route that moves moves for everyone at once.",
    )
    model_slug: constr(min_length=1, max_length=200)


class Cycle(ProtocolModel):
    """
    The round schedule, as block offsets. Expressed in blocks because the cycle is block-aligned rather than dependent only on wall clock: a validator whose clock runs fast would otherwise commit its challenge pack against a different randomness than its peers.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    blocks_per_day: conint(ge=1)
    submission_close_offset: int = Field(
        ..., description='Negative offsets precede T0. T-2h.'
    )
    salt_commit_offset: int = Field(..., description='T-90m.')
    randomness_offset: int = Field(
        ..., description='T-60m, post-deadline block randomness fixed.'
    )
    pack_commit_offset: int = Field(
        ..., description='T-20m, challenge pack hash committed.'
    )
    reveal_offset: int = Field(..., description='T0, validator-only bundle reveal.')
    execution_close_offset: int = Field(..., description='T+14h.')
    weights_offset: int = Field(..., description='T+23h.')
    anchor_block: conint(ge=0) = Field(
        ...,
        description="A block that is an epoch start: anchor_block % blocks_per_day == 0. With anchor_date it fixes the mapping from epoch index to calendar date, so a round's identity is derived from the chain rather than from a clock. Two validators either side of midnight would otherwise label the same round differently, fail to recognise each other's commitments, and generate packs they could not compare. Every validator on a subnet must share this pair.",
    )
    anchor_date: date = Field(
        ...,
        description='The ISO calendar date of the round beginning at anchor_block. A wrong value is not a consensus failure — every validator sharing it still agrees with every other — so nothing on chain would surface it; validator --check compares it against the clock at startup instead.',
    )


class Surface(Enum):
    openrouter = 'openrouter'


class MinerPricing(ProtocolModel):
    """
    RCC per unit of miner-funded usage. What the equal ceiling is denominated in.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rcc_per_1k_in: conint(ge=0) = Field(
        ...,
        description='RCC per thousand input tokens. 1,000 means one RCC is one input token, so the unit reads as input-token-equivalents. Flat across models by design (see gateway/metering.py): RCC measures reasoning volume, so an equal ceiling equalises how much thinking each laboratory may do rather than how much money it may spend.',
    )
    rcc_per_1k_out: conint(ge=0) = Field(
        ...,
        description='RCC per thousand output tokens. 5,000 is a 5x multiple of input, which is the real ratio for both Claude routes and the median across the eight routes measured (4.0x to 8.0x).',
    )
    rcc_per_search: conint(ge=0)
    allowed_model_slugs: list[constr(max_length=200)] | None = Field(
        None,
        description='Empty means any route OpenRouter offers. A non-empty list restricts it, and a slug absent from a non-empty list cannot be reached at all.',
        max_length=500,
    )
    maximum_rcc: conint(ge=1) = Field(
        ...,
        description="The RCC ceiling for one challenge, and therefore the basis of every comparison between laboratories (8, 13.6). Calibrated from measurement: one full five-idea portfolio synthesis against a frontier model costs about 200,000 RCC, and a laboratory that diverges, searches, critiques and then deepens costs roughly 800,000. A million leaves headroom for spending the budget well while keeping the reference template's single call at about a fifth of it.",
    )
    maximum_search_calls: conint(ge=0) = Field(
        ...,
        description='Search-call ceiling for one challenge. Counts against maximum_rcc as well.',
    )
    maximum_wall_time_seconds: conint(ge=1) = Field(
        ...,
        description='Wall-clock ceiling for one challenge, measured by the runner. A single frontier-model synthesis was measured at 214 seconds, so a laboratory making thirty calls needs either this much room or the parallelism its model manifest declares.',
    )


class ValidatorPurpose(Enum):
    challenge_generation = 'challenge_generation'
    critique = 'critique'
    judging = 'judging'
    prior_art = 'prior_art'


class Providers(ProtocolModel):
    """
    One provider surface, two accounts. Every model call in the subnet goes through OpenRouter; miners spend their own key and validators spend theirs.

    The separation is by *account*, not by provider, and it has to be enforced in code: with one provider a swapped key succeeds and silently bills the wrong party, where two providers would have failed on the first request.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    surface: Surface
    miner_pricing: MinerPricing = Field(
        ...,
        description='RCC per unit of miner-funded usage. What the equal ceiling is denominated in.',
    )
    validator_purposes: list[ValidatorPurpose] = Field(
        ...,
        description="What the validator's own key may be spent on. Purpose selects the credential, so this list is what a research call is checked against and refused by -- not documentation.",
        min_length=1,
    )


class Disclosure(ProtocolModel):
    """
    What is published after execution closes, and what stays sealed.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    publish_after_execution_close: list[str] | None = Field(None, max_length=40)
    judge_prompt_sealed_until_epoch_end: bool | None = Field(
        None,
        description='The detailed judge prompt may remain sealed to reduce immediate prompt overfitting. Its hash is committed at the start regardless, so it cannot be changed while sealed.',
    )


class Signing(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    registry_pubkey: constr(max_length=200)
    owner_hotkey: constr(max_length=100)
    ineligible_uids: list[conint(ge=0)] | None = Field(
        None,
        description='Owner-linked miner UIDs are ineligible. Declared here so the exclusion is public and auditable rather than an operational habit.',
        max_length=256,
    )


class CriterionWeightsPpm(ProtocolModel):
    """
    Must sum to 1000000.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    originality: conint(ge=0, le=1000000) = Field(..., description='25%')
    value: conint(ge=0, le=1000000) = Field(..., description='20%')
    mechanism: conint(ge=0, le=1000000) = Field(..., description='15%')
    constraint_fit: conint(ge=0, le=1000000) = Field(..., description='12%')
    diversity: conint(ge=0, le=1000000) = Field(..., description='10%')
    self_selection: conint(ge=0, le=1000000) = Field(..., description='8%')
    falsifiability: conint(ge=0, le=1000000) = Field(..., description='7%')
    cost_reliability: conint(ge=0, le=1000000) = Field(..., description='3%')


class Scoring(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pairwise_weight_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='0.75. Pairwise is the primary signal.'
    )
    pointwise_weight_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='0.25. Diagnostic anchoring: it reveals a weak field whose relative winner is still poor.',
    )
    mechanism_floor_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='0.40. Below this, value and originality are capped.'
    )
    capped_on_weak_mechanism_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='0.50. An idea cannot score highly merely by sounding unusual.'
    )
    daily_mean_weight_ppm: conint(ge=0, le=1000000) = Field(..., description='0.70.')
    daily_q25_weight_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='0.30. The lower quartile penalises a laboratory brilliant on one problem and failing the rest.',
    )
    rolling_short_days: conint(ge=1) = Field(..., description='7.')
    rolling_long_days: conint(ge=1) = Field(..., description='30.')
    rolling_short_weight_ppm: conint(ge=0, le=1000000) = Field(..., description='0.60.')
    rolling_long_weight_ppm: conint(ge=0, le=1000000) = Field(..., description='0.40.')
    minimum_days_for_median: conint(ge=1) = Field(
        ...,
        description='Below this many valid days, the rolling score is the plain mean. There is no credibility multiplier suppressing new miners, so this must not act as one: it selects an estimator, it does not scale a score.',
    )


class Panel(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criterion: str
    judges: list[Judge] = Field(..., min_length=3)
    reliability_floor_ppm: conint(ge=0, le=1000000) | None = Field(
        None, description='Parts per million. 1000000 = 1.0.'
    )


class Judging(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    minimum_families: conint(ge=3) = Field(
        ..., description='At least three. Two snapshots of one family are one family.'
    )
    family_cap_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='400000 = 40%. No single provider family may control more of a semantic criterion.',
    )
    panels: list[Panel] = Field(..., min_length=1)
    degradation_accuracy_floor_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='950000 = 95%. Below this a judge is removed from the panel.'
    )
    order_swap_inconsistency_ceiling_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='75000 = 7.5%.'
    )
    schema_validity_floor_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='990000 = 99%.'
    )
    circuit_breaker_consecutive_failures: conint(ge=1)


class WeightAllocation(ProtocolModel):
    """
    Softmax rather than proportional, so the gap between a strong and a mediocre laboratory matters more than their ratio.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    temperature_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='Tau in 0.08-0.12, so 80000-120000.'
    )
    maximum_weight_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='150000-200000. Overflow is redistributed, which encourages multiple lab architectures over one permanent winner.',
    )
    minimum_valid_challenges: conint(ge=1) = Field(
        ..., description='Being best among a handful of results is not qualification.'
    )
    burn_uid: conint(ge=0) = Field(
        ...,
        description='If no miner beats the reference floor, 100% of weight goes here. Paying nobody is a valid outcome and must be expressible.',
    )
    reference_floor_lab: constr(max_length=50) | None = Field(
        None,
        description='Which entry in reference_labs is the qualification floor of 20.1. Named rather than positional, so reordering the probe configurations cannot silently change the floor.',
    )


class ReferenceLab(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(max_length=50)
    container_digest: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    model_slug: constr(max_length=200)
    temperature_ppm: conint(ge=0, le=2000000) | None = Field(
        None,
        description="Sampling temperature in parts-per-million, so the probe's configuration carries no float into anything hashed.",
    )
    is_qualification_floor: bool | None = None


class SeasonConfig(ProtocolModel):
    """
    The public protocol the owner defines: taxonomy, resource classes, hard-gate rules, scoring formula, judge requirements, disclosure rules and version pins. Signed, hash-anchored on chain, and the only artifact a validator is permitted to derive rules from.

    The owner defines this and nothing else. It contains no challenges: the owner does not create the validation questions and does not grade answers. Anything resembling problem content in this file would reintroduce the owner as a trusted party.

    ## Every ratio is an integer in parts-per-million

    No field in this schema is typed `number`. A float serialises differently on two hosts, and this document is hashed and anchored — so a decimal here makes the anchor comparison fail for a reason nobody can locate. Writing ppm integers in the schema itself removes the conversion layer entirely, rather than converting decimals at load and hoping every reader converts the same way. The cost is readability: 250000 rather than 0.25. Each description states the decimal it means.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: Literal['AIL-3.0']
    season_id: constr(min_length=1, max_length=100)
    weights_version: conint(ge=1) = Field(
        ...,
        description='The on-chain version key. Bumped whenever the scoring formula changes, so a weight vector can be attributed to the rules that produced it.',
    )
    mechid: conint(ge=0) = Field(
        ...,
        description='Mechanism identifier. Passed on every weight and metagraph call; omitting it must raise before any network call.',
    )
    sdk_pin: constr(max_length=50)
    taxonomy: Taxonomy = Field(
        ...,
        description='The active domain set and the per-day stratification. V1 is restricted to domains an LLM panel can inspect without a physical laboratory.',
    )
    resource_classes: list[ResourceClass] = Field(..., min_length=1)
    challenge_generation: ChallengeGeneration = Field(
        ...,
        description="The generation pipeline's parameters. The discrimination probe is the load-bearing one: it is what stops a validator producing problems nobody can be scored on.",
    )
    criterion_weights_ppm: CriterionWeightsPpm = Field(
        ..., description='Must sum to 1000000.'
    )
    rank_weights_ppm: list[conint(ge=0, le=1000000)] = Field(
        ...,
        description='Per-idea weighting: 0.40, 0.25, 0.15, 0.12, 0.08. Ordered by rank, and must sum to 1000000. Length fixes the scored portfolio size.',
        max_length=10,
        min_length=1,
    )
    scoring: Scoring
    funnel: Funnel = Field(
        ...,
        description='The evaluation funnel. Every valid response gets the cheap anchored pointwise screen; only the cohort gets the expensive pairwise tournament. These numbers decide both what a round costs the validator and how much incumbency the ranking permits, which is why they are season configuration rather than constants: cohort_random and cohort_new exist so that being outside the top cannot become self-perpetuating.',
    )
    judging: Judging
    weight_allocation: WeightAllocation = Field(
        ...,
        description='Softmax rather than proportional, so the gap between a strong and a mediocre laboratory matters more than their ratio.',
    )
    cycle: Cycle = Field(
        ...,
        description='The round schedule, as block offsets. Expressed in blocks because the cycle is block-aligned rather than dependent only on wall clock: a validator whose clock runs fast would otherwise commit its challenge pack against a different randomness than its peers.',
    )
    reference_labs: list[ReferenceLab] = Field(
        ...,
        description="Configurations of the single reference template, by digest. The owner ships one miner template rather than four architectures; these are variations of it — different models, different temperatures — and they exist for two reasons. The first entry is the qualification floor of 20.1, pinned because a floor that could change without a rules change would silently move every miner's eligibility. The rest give 7.4 step 5's discrimination probe something to measure spread across: a probe with one configuration cannot tell an easy problem from a hard one, because condition 1 asks whether every reference produced essentially the same answer.",
        min_length=2,
    )
    providers: Providers | None = Field(
        None,
        description='One provider surface, two accounts. Every model call in the subnet goes through OpenRouter; miners spend their own key and validators spend theirs.\n\nThe separation is by *account*, not by provider, and it has to be enforced in code: with one provider a swapped key succeeds and silently bills the wrong party, where two providers would have failed on the first request.',
    )
    disclosure: Disclosure | None = Field(
        None,
        description='What is published after execution closes, and what stays sealed.',
    )
    signing: Signing
