"""Generated from protocol/schemas/. Do not edit by hand.

Regenerate with `python3 tools/gen_models.py`; `make schema` fails if this drifts from the
schema it was generated from. A schema change is a protocol change and requires bumping
`protocol_version`.
"""

# generated by datamodel-codegen:
#   filename:  season_config.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from protocol.model_base import ProtocolModel
from pydantic import ConfigDict, Field, RootModel, conint, constr


class Taxonomy(ProtocolModel):
    """
    The active domain set and the per-day stratification (section 7.2). V1 is restricted to domains an LLM panel can inspect without a physical laboratory.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    domains: list[str] = Field(..., max_length=32, min_length=1)
    challenges_per_day: conint(ge=1, le=64)
    stratification: dict[str, conint(ge=0)] = Field(
        ...,
        description='How many challenges each domain contributes per day. Must sum to `challenges_per_day`; a wildcard slot is expressed as the reserved domain name `wildcard`.',
    )
    excluded_domains: list[str] | None = Field(
        None,
        description="Section 2's V1 exclusions, named rather than merely omitted, so the safety filter has a list to check against.",
        max_length=32,
    )


class ResourceClass(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(max_length=50)
    memory_bytes: conint(ge=1)
    cpu_shares: conint(ge=1)
    pids_limit: conint(ge=1)
    workspace_bytes: conint(ge=0) | None = None


class Provider(Enum):
    """
    Always OpenRouter. Kept as a field rather than omitted so a future second surface is a schema change rather than a silent assumption.
    """

    openrouter = 'openrouter'


class Generator(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: constr(max_length=50)
    provider: Provider = Field(
        ...,
        description='Always OpenRouter. Kept as a field rather than omitted so a future second surface is a schema change rather than a silent assumption.',
    )
    model_snapshot: constr(max_length=200)
    slots: conint(ge=1)
    critic_family: constr(max_length=50) = Field(
        ...,
        description="Which family reviews this one's output. Must not be the family itself: same-family critique is close to self-review, since a model shares its generator's blind spots and rates its own family's output as well-formed. Crossing them is the only version of the check that finds an ambiguity the writer could not see.",
    )
    model_slug: constr(min_length=1, max_length=200) = Field(
        ...,
        description='The OpenRouter route, e.g. `openai/gpt-5`. `model_snapshot` pins which version of it.',
    )


class Backend(Enum):
    redis = 'redis'


class Store(ProtocolModel):
    """
    Where generated packs live (section 7.5). Redis: write a pack once, read it many times during execution, expire it after the dedup window, and survive a restart mid-round without losing a pack whose hash is already committed.

    `sandbox_reachable` must be false. A laboratory that could reach the store would read the entire pack -- every problem including ones it has not been issued, and other rounds' packs. The store is the validator's; delivery to the laboratory is the runner's, as its structured input.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    backend: Backend
    sandbox_reachable: Literal[False]
    pack_ttl_days: conint(ge=1) | None = None


class ChallengeGeneration(ProtocolModel):
    """
    Section 7.4's pipeline parameters. The discrimination probe is the load-bearing one: it is what stops a validator producing problems nobody can be scored on.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: constr(max_length=50)
    candidates_per_slot: conint(ge=1, le=10)
    dedup_lookback_days: conint(ge=1)
    duplicate_threshold_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='Similarity at or above which a candidate is a duplicate. 850000 = 0.85.',
    )
    minimum_reference_spread_ppm: conint(ge=0, le=1000000) | None = Field(
        None,
        description='Reference labs must disagree by at least this much, or the problem does not discriminate. Section 7.4 step 5.',
    )
    generator_model_snapshots: list[str] | None = Field(None, max_length=10)
    generators: list[Generator] = Field(
        ...,
        description="The two generator families and how many of the day's slots each owns (architecture.md section 7.2.1). Two rather than one because a single generator has a house style: it reaches for the same problem shapes and constraint patterns, and a laboratory tuned to that style scores well without being better. With half the pack from each family, half is always foreign to whatever a miner overfitted to -- and the gap between a miner's two halves is itself the earliest signal that the challenge supply has become predictable.",
        min_length=2,
    )
    store: Store = Field(
        ...,
        description="Where generated packs live (section 7.5). Redis: write a pack once, read it many times during execution, expire it after the dedup window, and survive a restart mid-round without losing a pack whose hash is already committed.\n\n`sandbox_reachable` must be false. A laboratory that could reach the store would read the entire pack -- every problem including ones it has not been issued, and other rounds' packs. The store is the validator's; delivery to the laboratory is the runner's, as its structured input.",
    )


class Provider1(Enum):
    openrouter = 'openrouter'


class Judge(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: constr(max_length=50) = Field(
        ...,
        description="Who trained the model behind the route, not the aggregator. Every judge is reached through OpenRouter, so reading 'provider' as the family would make the 40% cap vacuous: three routes to three Anthropic snapshots is one family and violates the cap however many distinct slugs it uses. The cap is evaluated on this field, which is why it is required rather than derived from the slug.",
    )
    provider: Provider1
    model_snapshot: constr(max_length=200)
    model_slug: constr(min_length=1, max_length=200)


class Cycle(ProtocolModel):
    """
    Section 21's daily schedule, as block offsets. Expressed in blocks because section 21 requires the cycle be block-aligned rather than dependent only on wall clock: a validator whose clock runs fast would otherwise commit its challenge pack against a different randomness than its peers.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    blocks_per_day: conint(ge=1)
    submission_close_offset: int = Field(
        ..., description='Negative offsets precede T0. Section 21: T-2h.'
    )
    salt_commit_offset: int = Field(..., description='T-90m.')
    randomness_offset: int = Field(
        ..., description='T-60m, post-deadline block randomness fixed.'
    )
    pack_commit_offset: int = Field(
        ..., description='T-20m, challenge pack hash committed.'
    )
    reveal_offset: int = Field(..., description='T0, validator-only bundle reveal.')
    execution_close_offset: int = Field(..., description='T+14h.')
    weights_offset: int = Field(..., description='T+23h.')


class Surface(Enum):
    openrouter = 'openrouter'


class MinerPricing(ProtocolModel):
    """
    RCC per unit of miner-funded usage. What the equal ceiling is denominated in.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rcc_per_1k_in: conint(ge=0)
    rcc_per_1k_out: conint(ge=0)
    rcc_per_search: conint(ge=0)
    allowed_model_slugs: list[constr(max_length=200)] | None = Field(
        None,
        description='Empty means any route OpenRouter offers. A non-empty list restricts it, and a slug absent from a non-empty list cannot be reached at all.',
        max_length=500,
    )


class ValidatorPurpose(Enum):
    challenge_generation = 'challenge_generation'
    critique = 'critique'
    judging = 'judging'
    prior_art = 'prior_art'


class Providers(ProtocolModel):
    """
    One provider surface, two accounts. Every model call in the subnet goes through OpenRouter; miners spend their own key and validators spend theirs.

    The separation is by *account*, not by provider, and section 3.4.4 explains why that now has to be enforced in code: with one provider a swapped key succeeds and silently bills the wrong party, where two providers would have failed on the first request.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    surface: Surface
    miner_pricing: MinerPricing = Field(
        ...,
        description='RCC per unit of miner-funded usage. What the equal ceiling is denominated in.',
    )
    validator_purposes: list[ValidatorPurpose] = Field(
        ...,
        description="What the validator's own key may be spent on. Purpose selects the credential (section 3.4.4 point 2), so this list is what a research call is checked against and refused by -- not documentation.",
        min_length=1,
    )


class Disclosure(ProtocolModel):
    """
    Section 22. What is published after execution closes, and what stays sealed.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    publish_after_execution_close: list[str] | None = Field(None, max_length=40)
    judge_prompt_sealed_until_epoch_end: bool | None = Field(
        None,
        description='Section 22: the detailed judge prompt may remain sealed to reduce immediate prompt overfitting. Its hash is committed at the start regardless, so it cannot be changed while sealed.',
    )


class Signing(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    registry_pubkey: constr(max_length=200)
    owner_hotkey: constr(max_length=100)
    ineligible_uids: list[conint(ge=0)] | None = Field(
        None,
        description='Section 23: owner-linked miner UIDs should be ineligible. Declared here so the exclusion is public and auditable rather than an operational habit.',
        max_length=256,
    )


class CriterionWeightsPpm(ProtocolModel):
    """
    Section 18.2. Must sum to 1000000.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    originality: conint(ge=0, le=1000000) = Field(..., description='25%')
    value: conint(ge=0, le=1000000) = Field(..., description='20%')
    mechanism: conint(ge=0, le=1000000) = Field(..., description='15%')
    constraint_fit: conint(ge=0, le=1000000) = Field(..., description='12%')
    diversity: conint(ge=0, le=1000000) = Field(..., description='10%')
    self_selection: conint(ge=0, le=1000000) = Field(..., description='8%')
    falsifiability: conint(ge=0, le=1000000) = Field(..., description='7%')
    cost_reliability: conint(ge=0, le=1000000) = Field(..., description='3%')


class Scoring(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pairwise_weight_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='Section 18.3, 0.75. Pairwise is the primary signal.'
    )
    pointwise_weight_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='0.25. Diagnostic anchoring: it reveals a weak field whose relative winner is still poor.',
    )
    mechanism_floor_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='Section 18.4, 0.40. Below this, value and originality are capped.',
    )
    capped_on_weak_mechanism_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='0.50. An idea cannot score highly merely by sounding unusual.'
    )
    daily_mean_weight_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='Section 18.5, 0.70.'
    )
    daily_q25_weight_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='0.30. The lower quartile penalises a laboratory brilliant on one problem and failing the rest.',
    )
    rolling_short_days: conint(ge=1) = Field(..., description='Section 18.6, 7.')
    rolling_long_days: conint(ge=1) = Field(..., description='30.')
    rolling_short_weight_ppm: conint(ge=0, le=1000000) = Field(..., description='0.60.')
    rolling_long_weight_ppm: conint(ge=0, le=1000000) = Field(..., description='0.40.')
    minimum_days_for_median: conint(ge=1) = Field(
        ...,
        description='Below this many valid days, the rolling score is the plain mean. Section 18.6 states there is no credibility multiplier suppressing new miners, so this must not act as one: it selects an estimator, it does not scale a score.',
    )


class Panel(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criterion: str
    judges: list[Judge] = Field(..., min_length=3)
    reliability_floor_ppm: conint(ge=0, le=1000000) | None = Field(
        None, description='Parts per million. 1000000 = 1.0.'
    )


class Judging(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    minimum_families: conint(ge=3) = Field(
        ...,
        description='Section 16.1: at least three. Two snapshots of one family are one family.',
    )
    family_cap_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='400000 = 40%. No single provider family may control more of a semantic criterion.',
    )
    panels: list[Panel] = Field(..., min_length=1)
    degradation_accuracy_floor_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='Section 19: 950000 = 95%. Below this a judge is removed from the panel.',
    )
    order_swap_inconsistency_ceiling_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='Section 27: 75000 = 7.5%.'
    )
    schema_validity_floor_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='990000 = 99%.'
    )
    circuit_breaker_consecutive_failures: conint(ge=1)


class WeightAllocation(ProtocolModel):
    """
    Section 20. Softmax rather than proportional, so the gap between a strong and a mediocre laboratory matters more than their ratio.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    temperature_ppm: conint(ge=0, le=1000000) = Field(
        ..., description='Section 20.2: tau in 0.08-0.12, so 80000-120000.'
    )
    maximum_weight_ppm: conint(ge=0, le=1000000) = Field(
        ...,
        description='Section 20.3: 150000-200000. Overflow is redistributed, which encourages multiple lab architectures over one permanent winner.',
    )
    minimum_valid_challenges: conint(ge=1) = Field(
        ...,
        description='Section 20.1. Being best among a handful of results is not qualification.',
    )
    burn_uid: conint(ge=0) = Field(
        ...,
        description='Section 20.4: if no miner beats the reference floor, 100% of weight goes here. Paying nobody is a valid outcome and must be expressible.',
    )
    reference_floor_lab: constr(max_length=50) | None = Field(
        None,
        description='Which entry in reference_labs is the qualification floor of 20.1. Named rather than positional, so reordering the probe configurations cannot silently change the floor.',
    )


class ReferenceLab(ProtocolModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(max_length=50)
    container_digest: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    model_slug: constr(max_length=200)
    temperature_ppm: conint(ge=0, le=2000000) | None = Field(
        None,
        description="Sampling temperature in parts-per-million, so the probe's configuration carries no float into anything hashed.",
    )
    is_qualification_floor: bool | None = None


class SeasonConfig(ProtocolModel):
    """
    The public protocol the owner defines (architecture.md section 3.3): taxonomy, resource classes, hard-gate rules, scoring formula, judge requirements, disclosure rules and version pins. Signed, hash-anchored on chain, and the only artifact a validator is permitted to derive rules from.

    The owner defines this and nothing else. It contains no challenges: section 3.3 is explicit that the owner does not create the daily validation questions and does not grade answers. Anything resembling problem content in this file would reintroduce the owner as a trusted party.

    ## Every ratio is an integer in parts-per-million

    No field in this schema is typed `number`. A float serialises differently on two hosts, and this document is hashed and anchored — so a decimal here makes the anchor comparison fail for a reason nobody can locate. Writing ppm integers in the schema itself removes the conversion layer entirely, rather than converting decimals at load and hoping every reader converts the same way. The cost is readability: 250000 rather than 0.25. Each description states the decimal it means.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: Literal['AIL-3.0']
    season_id: constr(min_length=1, max_length=100)
    weights_version: conint(ge=1) = Field(
        ...,
        description='The on-chain version key. Bumped whenever the scoring formula changes, so a weight vector can be attributed to the rules that produced it.',
    )
    mechid: conint(ge=0) = Field(
        ...,
        description='Mechanism identifier. Passed on every weight and metagraph call; omitting it must raise before any network call.',
    )
    sdk_pin: constr(max_length=50)
    taxonomy: Taxonomy = Field(
        ...,
        description='The active domain set and the per-day stratification (section 7.2). V1 is restricted to domains an LLM panel can inspect without a physical laboratory.',
    )
    resource_classes: list[ResourceClass] = Field(..., min_length=1)
    challenge_generation: ChallengeGeneration = Field(
        ...,
        description="Section 7.4's pipeline parameters. The discrimination probe is the load-bearing one: it is what stops a validator producing problems nobody can be scored on.",
    )
    criterion_weights_ppm: CriterionWeightsPpm = Field(
        ..., description='Section 18.2. Must sum to 1000000.'
    )
    rank_weights_ppm: list[conint(ge=0, le=1000000)] = Field(
        ...,
        description="Section 18.1's per-idea weighting: 0.40, 0.25, 0.15, 0.12, 0.08. Ordered by rank, and must sum to 1000000. Length fixes the scored portfolio size.",
        max_length=10,
        min_length=1,
    )
    scoring: Scoring
    judging: Judging
    weight_allocation: WeightAllocation = Field(
        ...,
        description='Section 20. Softmax rather than proportional, so the gap between a strong and a mediocre laboratory matters more than their ratio.',
    )
    cycle: Cycle = Field(
        ...,
        description="Section 21's daily schedule, as block offsets. Expressed in blocks because section 21 requires the cycle be block-aligned rather than dependent only on wall clock: a validator whose clock runs fast would otherwise commit its challenge pack against a different randomness than its peers.",
    )
    reference_labs: list[ReferenceLab] = Field(
        ...,
        description="Configurations of the single reference template (section 25), by digest. The owner ships one miner template rather than four architectures; these are variations of it — different models, different temperatures — and they exist for two reasons. The first entry is the qualification floor of 20.1, pinned because a floor that could change without a rules change would silently move every miner's eligibility. The rest give 7.4 step 5's discrimination probe something to measure spread across: a probe with one configuration cannot tell an easy problem from a hard one, because condition 1 asks whether every reference produced essentially the same answer.",
        min_length=2,
    )
    providers: Providers | None = Field(
        None,
        description='One provider surface, two accounts. Every model call in the subnet goes through OpenRouter; miners spend their own key and validators spend theirs.\n\nThe separation is by *account*, not by provider, and section 3.4.4 explains why that now has to be enforced in code: with one provider a swapped key succeeds and silently bills the wrong party, where two providers would have failed on the first request.',
    )
    disclosure: Disclosure | None = Field(
        None,
        description='Section 22. What is published after execution closes, and what stays sealed.',
    )
    signing: Signing
